"""Deterministic Internal Dev Kit starter-pack generator (T7).

No AI here - every file is built from Project fields, the intake form,
and fixed template text selected by project_type/classification. FR-016's
file list is frozen: exactly these 11 files, never more (see the "scope
regrowth" risk note in the vault MVP Implementation Plan).
"""

from app.registry.models import Project
from app.starterpack.schemas import GeneratedFile, IntakeForm
from app.vocab import REQUIRED_DOC_PROFILES, ArtifactType, Classification, ProjectType

_STACK_BY_TYPE: dict[ProjectType, str] = {
    ProjectType.INTERNAL_WEB_APP: "FastAPI backend, React/TypeScript frontend, PostgreSQL database - modular monolith.",
    ProjectType.OPERATIONAL_TOOL: "FastAPI (or script-triggered) backend, PostgreSQL if state is needed, minimal or no dedicated frontend.",
    ProjectType.PROTOTYPE: "Single minimal service - only add a frontend/database if validating the idea requires one.",
}

_DEPLOYMENT_BY_TYPE: dict[ProjectType, str] = {
    ProjectType.INTERNAL_WEB_APP: "NGINX reverse proxy, systemd-managed backend service, Docker Compose PostgreSQL - the standard CWS Internal Dev Kit pattern.",
    ProjectType.OPERATIONAL_TOOL: "systemd service or scheduled job on an internal VM; PostgreSQL only if the tool needs persistent state.",
    ProjectType.PROTOTYPE: "Local/developer machine only until the idea is validated - do not build production deployment for a prototype.",
}

_CLASSIFICATION_NOTE: dict[Classification, str] = {
    Classification.ONE_OFF: "This is a one-off build: scope narrowly to its stated purpose, not for reuse elsewhere.",
    Classification.REUSABLE: "This is intended to be reusable: keep configuration/branding separated from logic so other teams can adopt it.",
    Classification.PLATFORM: "This is a platform: treat breaking changes, versioning and multi-consumer impact as first-class concerns from day one.",
}

_ARTIFACT_LABELS: dict[ArtifactType, str] = {
    ArtifactType.USER_GUIDE: "user_guide",
    ArtifactType.ADMIN_GUIDE: "admin_guide",
    ArtifactType.DEVELOPER_GUIDE: "developer_guide",
    ArtifactType.AGENT_GUIDE: "agent_guide",
    ArtifactType.SUPPORT_RUNBOOK: "support_runbook",
    ArtifactType.DEPLOYMENT_GUIDE: "deployment_guide",
    ArtifactType.VERIFICATION_MATRIX: "verification_matrix",
    ArtifactType.EXIT_MD: "exit_md",
}


def _required_artifacts(project: Project) -> list[str]:
    required = REQUIRED_DOC_PROFILES.get(project.project_type, frozenset())
    return [_ARTIFACT_LABELS[a] for a in ArtifactType if a in required]


def _readme(project: Project, intake: IntakeForm) -> str:
    return f"""# {project.name}

{project.description or intake.workflow}

## What this is

- Users: {intake.users}
- Core workflow: {intake.workflow}
- Deployment target: {intake.deployment_target}

## Documentation

| Doc | Purpose |
|---|---|
| `docs/PROJECT_SCOPE.md` | MVP cut line, out-of-scope list |
| `docs/ARCHITECTURE.md` | Stack, shape, key decisions |
| `docs/DATA_MODEL.md` | Entities and controlled vocabularies |
| `docs/DEPLOYMENT.md` | How this gets deployed |
| `docs/OPERATIONS.md` | Running, monitoring, backup/restore |
| `docs/VERIFICATION_MATRIX.md` | What must be verified per task/phase |
| `AGENTS.md` | Operating rules for AI coding agents (canonical) |
| `EXIT.md` | Handover/exit state of this project |

## Status

Draft generated by the Internal Dev Kit starter-pack generator. Not yet reviewed - see FR-017.
"""


def _exit_md(project: Project, intake: IntakeForm) -> str:
    return f"""# EXIT.md - {project.name}

This file is the required DTO production/handover gate. It must be completed before production handover is considered complete.

Current status: **Draft - generated, not reviewed**.

## System owner

TBD.

## Business owner

{project.business_owner or "TBD."}

## Technical owner

{project.owner.name if project.owner else "TBD."}

## Runtime

Planned runtime pattern, pending final deployment approval:

{_DEPLOYMENT_BY_TYPE[project.project_type]}

## Environment variables

Document names only. Never commit real values.

- `APP_ENV`
- `APP_NAME`
- `DATABASE_URL`

## Data sensitivity

{intake.data_sensitivity}

## Deployment

Deployment is not complete. See `docs/DEPLOYMENT.md`.

## Backup and retention

TBD - define before production handover.

## Known risks

- Draft starter pack: content below is a deterministic first pass, not reviewed.
"""


def _opencode_md(project: Project) -> str:
    return f"""# OpenCode instructions - {project.name}

OpenCode-specific notes:

- Implement only the single task you were prompted with.
- Do not restructure packages, add dependencies, or change enum values without an explicit instruction.
- Leave verification evidence: which commands you ran and their results, appended to your task output.
"""


def _claude_md(project: Project) -> str:
    return f"""# Claude Code instructions - {project.name}

Follow `AGENTS.md` (canonical agent rules) and the read-first list there.

Claude-specific notes:

- Work one task at a time; confirm acceptance criteria before starting the next.
- Run tests and migrations against a fresh database before declaring a task complete.
- Do not commit or push unless the project owner asks.
"""


def _agents_md(project: Project, intake: IntakeForm) -> str:
    required = _required_artifacts(project)
    required_list = ", ".join(f"`{a}`" for a in required)
    return f"""# Agent instructions - {project.name}

Canonical operating rules for all AI coding agents working in this repository.

## Read first

1. `docs/PROJECT_SCOPE.md` - the MVP cut line.
2. `docs/DATA_MODEL.md` - entities and controlled vocabularies. Never invent enum values.
3. `docs/VERIFICATION_MATRIX.md` - what to verify before calling a task done.

## Project context

- Users: {intake.users}
- Core workflow: {intake.workflow}
- Integrations: {intake.integrations or "None recorded yet."}

## Hard rules

- {_STACK_BY_TYPE[project.project_type]}
- {_CLASSIFICATION_NOTE[project.classification]}
- Required documentation for this project type: {required_list}.

## Verification before "done"

- Migrations run clean on a fresh database.
- Tests pass.
- The affected flow is exercised end-to-end, not just unit-tested.
- No secret-like strings in code, fixtures or generated output.
"""


def _project_scope_md(project: Project, intake: IntakeForm) -> str:
    return f"""# Project scope - {project.name}

Draft generated by the starter-pack generator. Confirm and edit before treating as real scope.

## In scope

- {intake.workflow}
- Users: {intake.users}

## Out of scope (initial draft - confirm with the project owner)

- Anything not directly needed for the workflow above.
- Integrations beyond: {intake.integrations or "none recorded yet."}

## Notes

{intake.notes or "None recorded."}
"""


def _architecture_md(project: Project) -> str:
    return f"""# Architecture - {project.name}

## Shape

{_STACK_BY_TYPE[project.project_type]}

## Key decisions

| Decision | Choice |
|---|---|
| Classification | {project.classification.value} - {_CLASSIFICATION_NOTE[project.classification]} |
| Deployment | {_DEPLOYMENT_BY_TYPE[project.project_type]} |

This is a draft. Confirm the real architecture once the project is actually being built.
"""


def _data_model_md(project: Project) -> str:
    required = _required_artifacts(project)
    required_rows = "\n".join(f"| {a} | Required |" for a in required)
    return f"""# Data model - {project.name}

Draft generated by the starter-pack generator. Replace with the real entities and controlled vocabularies once defined.

## Entities

TBD - define entities here as the data model is designed.

## Required documentation profile for `{project.project_type.value}`

| artifact_type | required |
|---|---|
{required_rows}
"""


def _deployment_md(project: Project, intake: IntakeForm) -> str:
    return f"""# Deployment - {project.name}

## Target

{intake.deployment_target}

## Pattern

{_DEPLOYMENT_BY_TYPE[project.project_type]}

## Status

Not yet deployed. This is a draft generated before any real deployment work.
"""


def _operations_md(project: Project) -> str:
    return f"""# Operations - {project.name}

## Running locally

TBD - document the real run/start commands once the project is scaffolded.

## Health checks

TBD.

## Backup and restore

TBD - required before production handover (see `EXIT.md`).
"""


def _verification_matrix_md(project: Project) -> str:
    return f"""# Verification matrix - {project.name}

Every task records here what was verified, how, and by whom before it is called done.

## Standing checks (every task)

| Check | Command / method |
|---|---|
| Migrations clean on fresh DB | TBD |
| Tests pass | TBD |
| End-to-end exercise | Drive the affected API/UI flow, not only unit tests |
| No secrets | No secret-like strings in code, fixtures, generated output |

## Task verification log

| Task | Date | Verified by | Evidence |
|---|---|---|---|
| (none yet) | | | |
"""


def build_preview(project: Project, intake: IntakeForm) -> list[GeneratedFile]:
    """FR-015/FR-016: the frozen 11-file starter pack, deterministic only."""

    return [
        GeneratedFile(path="README.md", content=_readme(project, intake)),
        GeneratedFile(path="EXIT.md", content=_exit_md(project, intake)),
        GeneratedFile(path="OPENCODE.md", content=_opencode_md(project)),
        GeneratedFile(path="CLAUDE.md", content=_claude_md(project)),
        GeneratedFile(path="AGENTS.md", content=_agents_md(project, intake)),
        GeneratedFile(path="docs/PROJECT_SCOPE.md", content=_project_scope_md(project, intake)),
        GeneratedFile(path="docs/ARCHITECTURE.md", content=_architecture_md(project)),
        GeneratedFile(path="docs/DATA_MODEL.md", content=_data_model_md(project)),
        GeneratedFile(path="docs/DEPLOYMENT.md", content=_deployment_md(project, intake)),
        GeneratedFile(path="docs/OPERATIONS.md", content=_operations_md(project)),
        GeneratedFile(path="docs/VERIFICATION_MATRIX.md", content=_verification_matrix_md(project)),
    ]
