"""core tables: people, projects, project_members, audit_events

Revision ID: 2bc99a0c5cc8
Revises: 
Create Date: 2026-07-13 13:50:11.253627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2bc99a0c5cc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role_type', sa.Enum('admin', 'developer_project_owner', 'trainee', 'manager', 'end_user', 'auditor', 'ai_service_account', name='role'), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_purpose', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Enum('internal-web-app', 'operational-tool', 'prototype', name='project_type'), nullable=False),
    sa.Column('classification', sa.Enum('one-off', 'reusable', 'platform', name='classification'), nullable=False),
    sa.Column('phase', sa.Enum('concept', 'discovery', 'build', 'pilot', 'live', 'handover', 'retired', name='project_phase'), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', 'paused', 'complete', 'cancelled', name='project_status'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('business_owner', sa.String(length=200), nullable=True),
    sa.Column('current_next_action', sa.Text(), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('environment_url', sa.String(length=500), nullable=True),
    sa.Column('docs_url', sa.String(length=500), nullable=True),
    sa.Column('tech_stack_summary', sa.Text(), nullable=True),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('project_created', 'project_updated', 'status_event_created', 'doc_artifact_created', 'doc_artifact_updated', 'starter_pack_generated', 'starter_pack_reviewed', 'starter_pack_exported', 'ai_run_created', 'ai_output_reviewed', 'seed_import_run', 'member_added', 'member_removed', name='audit_action_type'), nullable=False),
    sa.Column('object_type', sa.Enum('project', 'status_event', 'documentation_artifact', 'starter_pack', 'ai_interaction', 'project_member', 'job', name='audit_object_type'), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'developer_project_owner', 'trainee', 'manager', 'end_user', 'auditor', 'ai_service_account', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'person_id', name='uq_project_person')
    )
    op.create_index(op.f('ix_project_members_person_id'), 'project_members', ['person_id'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_person_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
