"""starter packs and ai interactions

Revision ID: 3f35c1d25e2e
Revises: 4ab1e74e4ec3
Create Date: 2026-07-13 21:01:18.372922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3f35c1d25e2e'
down_revision: Union[str, None] = '4ab1e74e4ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('project_summary', 'starter_pack_tailoring', name='ai_task_type'), nullable=False),
    sa.Column('audience', sa.Enum('developer', 'manager', name='ai_audience'), nullable=True),
    sa.Column('prompt_id', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('source_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_bundle_hash', sa.Text(), nullable=False),
    sa.Column('model_provider', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_category', sa.Enum('provider_unavailable', 'timeout', 'rate_limited', 'context_too_large', 'malformed_output', 'validation_failed', 'forbidden_data_detected', 'access_denied', 'budget_exceeded', 'internal_error', name='error_category'), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.Enum('passed', 'failed_schema', 'failed_missing_sources', 'failed_forbidden_data', name='validation_status'), nullable=False),
    sa.Column('human_review_status', sa.Enum('generated', 'reviewed', 'exported', 'rejected', name='human_review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interactions_project_id'), 'ai_interactions', ['project_id'], unique=False)
    op.create_table('starter_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('intake_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_files_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('export_path', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('generated', 'reviewed', 'exported', 'rejected', name='human_review_status', create_type=False), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starter_packs_project_id'), 'starter_packs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_starter_packs_project_id'), table_name='starter_packs')
    op.drop_table('starter_packs')
    op.drop_index(op.f('ix_ai_interactions_project_id'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    # ### end Alembic commands ###

    # All five enum types below are created fresh by this migration's
    # create_table calls - drop them explicitly or a later upgrade will hit
    # "type already exists" (see the T5 migration for the same lesson).
    for enum_name in (
        'ai_task_type', 'ai_audience', 'error_category', 'validation_status', 'human_review_status',
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
