"""documentation matrix tables

Revision ID: 4ab1e74e4ec3
Revises: 80af178c7a75
Create Date: 2026-07-13 17:43:18.135111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '4ab1e74e4ec3'
down_revision: Union[str, None] = '80af178c7a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('required_doc_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_type', postgresql.ENUM('internal-web-app', 'operational-tool', 'prototype', name='project_type', create_type=False), nullable=False),
    sa.Column('artifact_type', sa.Enum('user_guide', 'admin_guide', 'developer_guide', 'agent_guide', 'support_runbook', 'deployment_guide', 'verification_matrix', 'exit_md', name='artifact_type'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_type', 'artifact_type', name='uq_doc_profile_type')
    )
    op.create_table('documentation_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.Enum('user_guide', 'admin_guide', 'developer_guide', 'agent_guide', 'support_runbook', 'deployment_guide', 'verification_matrix', 'exit_md', name='artifact_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('missing', 'draft', 'current', 'stale', 'approved', 'retired', name='artifact_status'), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('staleness_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'artifact_type', name='uq_doc_artifact_project_type')
    )
    op.create_index(op.f('ix_documentation_artifacts_project_id'), 'documentation_artifacts', ['project_id'], unique=False)
    # ### end Alembic commands ###

    _seed_required_doc_profiles()


# Mirrors app.vocab.REQUIRED_DOC_PROFILES exactly (the vocab law) - this
# table exists so each project_type/artifact_type pairing can carry its
# own notes and be inspected without a code change, not to diverge from it.
_ARTIFACT_TYPES = [
    'user_guide', 'admin_guide', 'developer_guide', 'agent_guide',
    'support_runbook', 'deployment_guide', 'verification_matrix', 'exit_md',
]
_REQUIRED_BY_PROJECT_TYPE = {
    'internal-web-app': set(_ARTIFACT_TYPES),
    'operational-tool': {
        'developer_guide', 'agent_guide', 'support_runbook',
        'deployment_guide', 'verification_matrix', 'exit_md',
    },
    'prototype': {'agent_guide', 'exit_md'},
}


def _seed_required_doc_profiles() -> None:
    table = sa.table(
        'required_doc_profiles',
        sa.column(
            'project_type',
            postgresql.ENUM(
                'internal-web-app', 'operational-tool', 'prototype',
                name='project_type', create_type=False,
            ),
        ),
        sa.column(
            'artifact_type',
            postgresql.ENUM(*_ARTIFACT_TYPES, name='artifact_type', create_type=False),
        ),
        sa.column('required', sa.Boolean),
    )
    rows = [
        {
            'project_type': project_type,
            'artifact_type': artifact_type,
            'required': artifact_type in required_set,
        }
        for project_type, required_set in _REQUIRED_BY_PROJECT_TYPE.items()
        for artifact_type in _ARTIFACT_TYPES
    ]
    op.bulk_insert(table, rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentation_artifacts_project_id'), table_name='documentation_artifacts')
    op.drop_table('documentation_artifacts')
    op.drop_table('required_doc_profiles')
    # ### end Alembic commands ###

    # artifact_type/artifact_status are created fresh by this migration's
    # create_table calls (unlike project_type, which already existed) - drop
    # them explicitly or a later upgrade will hit "type already exists".
    postgresql.ENUM(name='artifact_type').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='artifact_status').drop(op.get_bind(), checkfirst=True)
