"""status events table

Revision ID: 80af178c7a75
Revises: c3e9ed123901
Create Date: 2026-07-13 17:03:49.516541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80af178c7a75'
down_revision: Union[str, None] = 'c3e9ed123901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('completed_work', sa.Text(), nullable=True),
    sa.Column('next_actions', sa.Text(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_events_project_id'), 'status_events', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_events_project_id'), table_name='status_events')
    op.drop_table('status_events')
    # ### end Alembic commands ###
